default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: onebitforms_development

test:
  <<: *default
  database: onebitforms_test

production:
  <<: *default
  database: onebitforms_production
